version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
         root: .
         paths:
            - .
  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - attach_workspace:
          at: .
      - run: pip3 install ansible boto boto3
      - run:
         command: |
          sudo pip install boto boto3
      - add_ssh_keys:
         fingerprints:
          - ""
      - ansible-playbook/playbook:
          playbook: ansible/ec2_deploy.yml
          playbook-options: --user ubuntu
workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
